version: '3'
services:
  app:
    build:
      context: .
    environment:
      - RAILS_ENV=development
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/clickerapp
      - public-data:/clickerapp/public
      - tmp-data:/clickerapp/tmp
      - log-data:/clickerapp/log
    depends_on:
      - redis
  redis:
    image: redis:3.2.9
    ports:
      - "6379:6379"
    command: redis-server

  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/clickerapp/public
      - tmp-data:/clickerapp/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  log-data:
